version: '3'
services:
  db:
    image: postgres
    container_name: social-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework
    ports:
      - "5435:5432"
