spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/homework
  flyway:
    locations: classpath:db.migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  secret: "SECRET"

logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:
server:
  port: 8083